[project]
name = "capstone"
version = "0.1.0"
description = "MLOps Capstone Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc>=3.61.0",
    "fastapi[standard]>=0.116.1",
    "granian>=2.5.0",
    "polars>=1.31.0",
    "structlog>=25.4.0",
    "torch>=2.7.1",
    "watchfiles>=1.1.0",
]

[dependency-groups]
dev = ["jupyterlab>=4.4.5"]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
