all:
  vars:

deploycamp:
  hosts:
    deploycamp_a:
      ansible_host: deploycamp

      security_ssh_allowed_users:
        - ubuntu
      security_sudoers_passwordless:
        - root
        - ubuntu

      firewall_flush_rules_and_chains: false

      firewall_allowed_tcp_ports:
        - "22"
        - "80"
        - "443"

      docker_users:
        - ubuntu

      bootstrap_hostname: deploycamp_server_a
